blueprint:
  name: Check Keypad Code with PIN and Execute Custom Actions
  description: Compares the code from a keypad text entity with a predefined PIN when a boolean `haschanged` is true, then executes custom actions defined by the user.
  domain: automation
  input:
    haschanged_boolean:
      name: Has Changed Boolean
      description: The boolean entity that indicates if the keypad code has changed.
      selector:
        entity:
          domain: input_boolean
    keypad_code_sensor:
      name: Keypad Code Sensor
      description: The sensor entity that stores the keypad code.
      selector:
        entity:
          domain: sensor
    pin_code:
      name: PIN Code
      description: The predefined PIN code to compare with the keypad code.
      selector:
        text:
    custom_actions:
      name: Custom Actions
      description: The actions to execute when the correct PIN is entered.
      selector:
        action: {}

trigger:
  - platform: state
    entity_id: !input haschanged_boolean
    to: 'on'
condition:
  - condition: template
    value_template: "{{ is_state(input('haschanged_boolean'), 'on') }}"
  - condition: template
    value_template: "{{ states(input('keypad_code_sensor')) == input('pin_code') }}"
action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ states(input('keypad_code_sensor')) == input('pin_code') }}"
        sequence: !input custom_actions
mode: single
